### ISSUE TITLE
Signingkey is public

### ISSUE THREAD

**Issue by jobintweets** [hussainweb/dotfiles-basic-script#3]
The signing key credentials are visible in .gitconfig file.

**Comment by hussainweb** [comment]
Hey, thanks for pointing this out. If you mean [line 4 in the .gitconfig file](https://github.com/hussainweb/dotfiles/blob/497a10c14c71ead3d067a68ec84c18b05e45c294/git/.gitconfig#L4), that is just the identifier for the public part of the key. This is in fact shared with services that verify the commits as my own. To my knowledge, this is not a risk. I am happy to hear your thoughts on this if you think otherwise.

Thanks again for raising this.
